# Generated by Django 4.0.5 on 2022-06-23 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_additional_address_user_city_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='Fablab',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('14', 'Calvados'), ('22', "Côtes d'armor"), ('29', 'Finistère'), ('35', 'Ile-et-Vilaine'), ('44', 'Loire Atlantique'), ('49', 'Maine-et-Loire'), ('50', 'Manche'), ('53', 'Mayenne'), ('56', 'Morbihan'), ('61', 'Orne'), ('72', 'Sarthe'), ('85', 'Vendée')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='additional_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Complément d'adresse"),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de voie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_route',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='N° de voie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('FABLAB', 'Fablab')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='FablabMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fablab', models.CharField(max_length=128, verbose_name='Nom du FabLab')),
                ('presentation_fablab', models.TextField(verbose_name='Présentation')),
                ('skills_fablab', models.CharField(max_length=255, verbose_name='Domaine de compétences')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nom')),
                ('type_organization', models.CharField(blank=True, max_length=128, null=True, verbose_name="Type d'organisation")),
                ('name_organization', models.CharField(blank=True, max_length=128, null=True, verbose_name="Nom de l'organisation")),
                ('web_site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Web site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
