# Generated by Django 4.0.5 on 2022-06-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_applicant_fablab_user_department_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantMore',
            new_name='ApplicantUser',
        ),
        migrations.RenameModel(
            old_name='FablabMore',
            new_name='FablabUser',
        ),
    ]
