# Generated by Django 4.0.5 on 2022-06-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_applicantmore_applicantuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('FABLAB', 'Fablab'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
