# Generated by Django 4.0.5 on 2022-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_type_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='department',
            field=models.CharField(choices=[('14', 'Calvados'), ('22', "Côtes d'armor"), ('29', 'Finistère'), ('35', 'Ile-et-Vilaine'), ('44', 'Loire Atlantique'), ('49', 'Maine-et-Loire'), ('50', 'Manche'), ('53', 'Mayenne'), ('56', 'Morbihan'), ('61', 'Orne'), ('72', 'Sarthe'), ('85', 'Vendée')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='phone_number',
            field=models.CharField(default='', max_length=10, verbose_name='Téléphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='department',
            field=models.CharField(choices=[('14', 'Calvados'), ('22', "Côtes d'armor"), ('29', 'Finistère'), ('35', 'Ile-et-Vilaine'), ('44', 'Loire Atlantique'), ('49', 'Maine-et-Loire'), ('50', 'Manche'), ('53', 'Mayenne'), ('56', 'Morbihan'), ('61', 'Orne'), ('72', 'Sarthe'), ('85', 'Vendée')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='phone_number',
            field=models.CharField(default='', max_length=10, verbose_name='Téléphone'),
            preserve_default=False,
        ),
    ]
