# Generated by Django 4.0.5 on 2022-06-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_department_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Fablab',
        ),
        migrations.RenameField(
            model_name='fablabuser',
            old_name='name_fablab',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='fablabuser',
            name='presentation_fablab',
        ),
        migrations.RemoveField(
            model_name='fablabuser',
            name='skills_fablab',
        ),
        migrations.RemoveField(
            model_name='user',
            name='additional_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_route',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_route',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type_user',
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='additional_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Complément d'adresse"),
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='name_route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de voie'),
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='number_route',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='N° de voie'),
        ),
        migrations.AddField(
            model_name='applicantuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='additional_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Complément d'adresse"),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='name_route',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de voie'),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='number_route',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='N° de voie'),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='presentation',
            field=models.TextField(default='', max_length=255, verbose_name='Présentation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site internet'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_fablab',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='department',
            field=models.CharField(choices=[('14', '14 - Calvados'), ('22', "22 - Côtes d'armor"), ('29', '29 - Finistère'), ('35', '35 - Ile-et-Vilaine'), ('44', '44 - Loire Atlantique'), ('49', '49 - Maine-et-Loire'), ('50', '50 - Manche'), ('53', '53 - Mayenne'), ('56', '56 - Morbihan'), ('61', '61 - Orne'), ('72', '72 - Sarthe'), ('85', '85 - Vendée')], max_length=50),
        ),
        migrations.AlterField(
            model_name='applicantuser',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site internet'),
        ),
        migrations.AlterField(
            model_name='fablabuser',
            name='department',
            field=models.CharField(choices=[('14', '14 - Calvados'), ('22', "22 - Côtes d'armor"), ('29', '29 - Finistère'), ('35', '35 - Ile-et-Vilaine'), ('44', '44 - Loire Atlantique'), ('49', '49 - Maine-et-Loire'), ('50', '50 - Manche'), ('53', '53 - Mayenne'), ('56', '56 - Morbihan'), ('61', '61 - Orne'), ('72', '72 - Sarthe'), ('85', '85 - Vendée')], max_length=50),
        ),
    ]
