# Generated by Django 4.0.5 on 2022-07-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_applicantuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuser',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Adresse mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Adresse mail'),
            preserve_default=False,
        ),
    ]
