# Generated by Django 4.0.5 on 2022-08-31 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_applicantuser_email_fablabuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fablabuser',
            name='email',
        ),
    ]
