# Generated by Django 4.0.5 on 2022-09-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_applicantuser_email_remove_fablabuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Adresse mail'),
        ),
        migrations.AddField(
            model_name='fablabuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Adresse mail'),
        ),
    ]
