# Generated by Django 4.0.5 on 2022-06-12 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('number_route', models.CharField(blank=True, max_length=10, null=True)),
                ('name_route', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_address', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fablab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_fablab', models.CharField(max_length=128)),
                ('department', models.CharField(choices=[('14', 'Calvados'), ('22', 'Cotes Darmor'), ('29', 'Finistere'), ('35', 'Ile Et Vilaine'), ('44', 'Loire Atlantique'), ('49', 'Maine Et Loire'), ('50', 'Manche'), ('53', 'Mayenne'), ('56', 'Morbihan'), ('61', 'Orne'), ('72', 'Sarthe'), ('85', 'Vendee')], max_length=50)),
                ('presentation_fablab', models.TextField()),
                ('skills_fablab', models.CharField(max_length=255)),
                ('phone_fablab', models.CharField(max_length=10)),
                ('mail_fablab', models.EmailField(max_length=254)),
                ('password_fablab', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_organization', models.CharField(max_length=128)),
                ('name_organization', models.CharField(max_length=128)),
                ('number_route_organization', models.IntegerField(blank=True, null=True)),
                ('name_route_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_address_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode_organization', models.IntegerField(blank=True, null=True)),
                ('city_organization', models.CharField(blank=True, max_length=128, null=True)),
                ('web_site', models.CharField(max_length=255)),
                ('phone_organization', models.CharField(max_length=10)),
                ('mail_organization', models.EmailField(max_length=254)),
                ('password_organization', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_title', models.CharField(max_length=255)),
                ('request_detail', models.TextField()),
                ('applicant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateform.applicant')),
                ('prescriber_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateform.prescriber')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('second_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name_leader_project', models.CharField(max_length=125)),
                ('last_name_leader_project', models.CharField(max_length=125)),
                ('phone_leader_project', models.CharField(max_length=10)),
                ('mail_leader_project', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('fablab_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateform.fablab')),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plateform.request')),
            ],
        ),
    ]
