# Generated by Django 4.0.5 on 2022-06-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='fablab_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='applicant_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='prescriber_id',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_detail',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Fablab',
        ),
        migrations.DeleteModel(
            name='Prescriber',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
