# Generated by Django 4.0.5 on 2022-06-09 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
