# Generated by Django 4.0.5 on 2022-06-09 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0002_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
