# Generated by Django 4.0.5 on 2022-06-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0003_test_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='second_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
