# Generated by Django 4.0.5 on 2022-06-09 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0004_test_second_updated_alter_test_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('number_route', models.CharField(max_length=10, null=True)),
                ('name_route', models.CharField(max_length=255, null=True)),
                ('additional_address', models.CharField(max_length=255, null=True)),
                ('postcode', models.IntegerField(max_length=5, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
