# Generated by Django 4.0.5 on 2022-07-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0006_alter_request_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
