# Generated by Django 4.0.5 on 2022-06-10 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0006_alter_applicant_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_organization', models.CharField(max_length=128)),
                ('name_organization', models.CharField(max_length=128)),
                ('number_route_organization', models.IntegerField(blank=True)),
                ('name_route_organization', models.CharField(blank=True, max_length=255)),
                ('additional_address_organization', models.CharField(blank=True, max_length=255)),
                ('postcode_organization', models.IntegerField(blank=True)),
                ('city_organization', models.CharField(max_length=128)),
                ('web_site', models.CharField(max_length=255)),
                ('phone_organization', models.CharField(max_length=10)),
                ('mail_organization', models.CharField(max_length=128)),
                ('password_organization', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='additional_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name_route',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='number_route',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='postcode',
            field=models.IntegerField(blank=True),
        ),
    ]
