# Generated by Django 4.0.5 on 2022-06-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0007_prescriber_alter_applicant_additional_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
