# Generated by Django 4.0.5 on 2022-08-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0007_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='categorie',
            field=models.CharField(choices=[('ATI', 'Aides techniques'), ('ATO', 'Aides technologiques'), ('ADO', 'Aides domotiques'), ('GBA', 'Gabarits')], default='', max_length=55, verbose_name='Catégorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='contrainte',
            field=models.CharField(choices=[('NR', 'Pas de contrainte identifiée'), ('NA', 'Normes alimentaires')], default='', max_length=55, verbose_name='Contrainte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='matiere',
            field=models.CharField(choices=[('NR', 'Pas de matière prédéfinie'), ('TX', 'Textile'), ('MT', 'Métal'), ('PL', 'Plastique'), ('BO', 'Bois')], default='', max_length=55, verbose_name='Matière'),
            preserve_default=False,
        ),
    ]
