# Generated by Django 4.0.5 on 2022-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0008_alter_applicant_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='city_organization',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='number_route_organization',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
