# Generated by Django 4.0.5 on 2022-06-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0009_alter_prescriber_city_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='additional_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name_route',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='number_route',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='additional_address_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='city_organization',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='name_route_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='postcode_organization',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
