# Generated by Django 4.0.5 on 2022-06-10 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0010_alter_applicant_additional_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fablab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_fablab', models.CharField(max_length=128)),
                ('department', models.CharField(choices=[('14', 'Calvados'), ('22', 'Cotes Darmor'), ('29', 'Finistere'), ('35', 'Ile Et Vilaine'), ('44', 'Loire Atlantique'), ('49', 'Maine Et Loire'), ('50', 'Manche'), ('53', 'Mayenne'), ('56', 'Morbihan'), ('61', 'Orne'), ('72', 'Sarthe'), ('85', 'Vendee')], max_length=50)),
                ('presentation_fablab', models.CharField(max_length=1000)),
                ('skills_fablab', models.CharField(max_length=255)),
                ('phone_fablab', models.IntegerField()),
                ('mail_fablab', models.CharField(max_length=125)),
                ('password_fablab', models.CharField(max_length=125)),
            ],
        ),
    ]
