# Generated by Django 4.0.5 on 2022-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0011_fablab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fablab',
            name='mail_fablab',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='fablab',
            name='phone_fablab',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fablab',
            name='presentation_fablab',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='mail_organization',
            field=models.EmailField(max_length=254),
        ),
    ]
