# Generated by Django 4.0.5 on 2022-06-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0013_alter_applicant_id_alter_fablab_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Response',
        ),
    ]
