# Generated by Django 4.0.5 on 2022-06-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plateform', '0015_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_detail',
            field=models.TextField(),
        ),
    ]
